{{-- The form fields are generated by custom form components registered with the FormServiceProvider --}}

{{ Form::inputBlock($user, 'name', 'Name', ['required' => 'required']) }}
{{ Form::inputBlock($user, 'email', 'E-Mail Address', ['required' => 'required']) }}
{{ Form::passwordBlock($user, 'password', 'Password') }}
{{ Form::submit('Save') }}
