@if(!empty($user))
    {{ Form::model($user, ['route' => ['users.update', $user], 'method' => 'put']) }}
@else
    {!! Form::open(['route' => 'users.store']) !!}
@endif

{{-- The form fields are generated by custom form components registered with the FormServiceProvider --}}

{{ Form::inputBlock($user, 'name', 'Name', ['required' => 'required'])}}
{{ Form::inputBlock($user, 'email', 'E-Mail Address', ['required' => 'required'])}}
{{ Form::inputBlock($user, 'password', 'Password', ['required' => 'required'])}}
{{ Form::inputBlock($user, 'password_confirmation', 'Confirm Password', ['required' => 'required'])}}
{{ Form::textareaBlock($user, 'bio', 'Biography', [])}}       

{{ Form::close() }}
